manul intervention added

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -40,6 +40,7 @@ stages:
   jobs:
   - job: TrivyScan
     displayName: 'Run Trivy Scan'
+    continueOnError: true
     pool:
       vmImage: 'ubuntu-latest'
     steps:
@@ -76,24 +77,40 @@ stages:
       condition: always()
 
 - stage: AdminIntervention
+  displayName: 'Admin Intervention'
   dependsOn: TrivyScanSec
   condition: failed()
-  displayName: 'Prompt for user input'
   jobs:
-  - job: Prompt
-    displayName: 'Prompt for admin intervention'
+  - job: PromptForApproval
+    displayName: 'Prompt for approval'
+    timeoutInMinutes: 60
     pool:
       vmImage: 'ubuntu-latest'
     steps:
-    - script: |
-        echo "Trivy scan failed. Do you want to continue?"
-        select yn in "Yes" "No"; do
-          case $yn in
-            Yes ) echo "Continuing pipeline..."; exit 0;;
-            No ) echo "Stopping pipeline..."; exit 1;;
-          esac
-        done
-        
+    - task: ManualIntervention@1
+      inputs:
+        instructions: 'Trivy scan failed. Do you want to continue?'
+
+# - stage: AdminIntervention
+#   dependsOn: TrivyScanSec
+#   condition: failed()
+#   displayName: 'Prompt for user input'
+#   jobs:
+#   - job: Prompt
+#     displayName: 'Prompt for admin intervention'
+#     pool:
+#       vmImage: 'ubuntu-latest'
+#     steps:
+#     - script: |
+#         echo "Trivy scan failed. Do you want to continue?"
+#         select yn in "Yes" "No"; do
+#           case $yn in
+#             Yes ) echo "Continuing pipeline..."; exit 0;;
+#             No ) echo "Stopping pipeline..."; exit 1;;
+#           esac
+#         done
+
+
 # Deploy to QA
 - stage: DeployQA
   dependsOn: AdminIntervention
